<?php

/**
 * Implements hook_views_api().
 */
function views_rss_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'views_rss') . '/views',
  );
}

/**
 * Implements hook_theme().
 */
function views_rss_theme() {
  $path = drupal_get_path('module', 'views_rss');
  return array(
    'views_rss_fields_item' => array(
      'variables' => array('item' => NULL),
      'file' => 'views_rss_views_fields.theme.inc',
      'path' => "$path/views",
    ),
    'views_rss_fields_element' => array(
      'variables' => array('key' => NULL, 'element' => NULL),
      'file' => 'views_rss_views_fields.theme.inc',
      'path' => "$path/views",
    ),
    'views_rss_feed_icon' => array(
      'variables' => array('url', 'title', 'icon'),
      'file' => 'views_rss_views_fields.theme.inc',
      'path' => "$path/views",
    ),
    'views_rss_feed_description' => array(
      'variables' => array('description', 'view'),
      'file' => 'views_rss_views_fields.theme.inc',
      'path' => "$path/views",
    ),
  );
}
