<?php

/**
 * @file
 * (Un)installation functions for Views RSS: DC Elements module.
 */

use Drupal\Core\Cache\CacheBackendInterface;

/**
 * Implements hook_install().
 */
function views_rss_dc_install() {
  \Drupal::cache('data')->invalidateTags(array('views_rss'));
}

/**
 * Implements hook_uninstall().
 */
function views_rss_dc_uninstall() {
  \Drupal::cache('data')->invalidateTags(array('views_rss'));
}
